import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Inter } from "next/font/google";
import { LoginProvider } from "@/context/login";
import { ThemeProvider } from "@/context/theme";
import { Box } from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  subsets: ["vietnamese"],
  variable: "--inter-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Provider>
          <LoginProvider>
            <ThemeProvider>
              <Box minH={"svh"}>{children}</Box>
              <Toaster />
            </ThemeProvider>
          </LoginProvider>
        </Provider>
      </body>
    </html>
  );
}
